version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: mysql-timesat
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwordRoot
    networks:
      network-proj-timesat:
        ipv4_address: 173.20.0.2
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8000:80
    depends_on:
      - db
  # environment:
      #PMA_ARBITRARY: 1
    networks:
      network-proj-timesat:
        ipv4_address: 173.20.0.3
networks:
  network-proj-timesat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.20.0.0/24
